source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'bundler', '>= 1.10.6'
gem 'rails', '>= 4.2.4'
gem 'sqlite3', '>= 1.3.10'
gem 'mysql2', '>= 0.4.1'
gem 'sass-rails', '>= 5.0.4'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '>= 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'haml', '>= 4.0.7'
gem 'react-rails', '>= 1.3.1'

# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 4.0.5'
#gem 'turbolinks'
gem 'jbuilder', '>= 2.3.1'
gem 'sdoc', '>= 0.4.1', group: :doc

# Use Capistrano for deployment
group :development do
  gem 'capistrano-rails', '>= 1.1.3'
  gem 'capistrano-rvm', '>= 0.1.2'
end

gem 'compass-rails', '>= 2.0.5'
gem 'slim-rails', '>= 3.0.1'
gem 'sorcery', '>= 0.9.1'
gem 'carrierwave', '>= 0.10.0'
gem 'cancan', '>= 1.6.10'
gem 'rack-cors', '>= 0.4.0', require: 'rack/cors'

# Admin interface
gem 'activeadmin', '>= 1.0.0.pre1'
gem 'devise', '>= 3.5.2'
gem 'country_select', '>= 2.4.0'

gem 'friendly_id', '>= 5.1.0'

source 'http://rails-assets.org' do
  gem 'rails-assets-bootstrap', '>= 3.3.5'
  gem 'rails-assets-font-awesome', '>= 4.4.0'
end

group :development, :test do
  gem 'rspec-rails', '>= 3.3.3'

  gem 'byebug', '>= 6.0.2'
  gem 'web-console', '>= 2.2.1'
  gem 'spring', '>= 1.4.0'
  gem 'rubocop', '>= 0.34.2'
end

